### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/botanical-machinery#48]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [x] @noeppi-noeppi 
- [x] @Fodoth-jinzi89

**Comment by Fodoth-jinzi89** [comment]
Agreed.
——Fodoth_jinzi89



At 2021-09-11 19:11:28, "MelanX" ***@***.***> wrote:

I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
@noeppi-noeppi
@Fodoth-jinzi89

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by noeppi-noeppi** [comment]
I approve that you change the license to Apache 2.0 for the project botanical-machinery.
