### ISSUE TITLE
Blacklist for Mechanical Daisy

### ISSUE THREAD

**Issue by Saereth** [MelanX/botanical-machinery#64]
### Describe your idea

I noticed you cant insert living wood for example, into the mechanical daisy, this prevents a conversion loop from happening. There is another mod called Botanical Additions that adds an elven wood to dreamwood conversion but since dreamwood isnt blacklisted it will continue on converting to normal living wood after. Would it be possible to get a tag blacklist so we can tag conversions like this to stop them from happening? Would be very useful.

**Comment by MelanX** [comment]
What about another way: Only start a new recipe after the previous result was taken. So, you need to place a new input before it's processing again. *Could* break some existing automations, I could add a config value to disable this.

**Comment by noeppi-noeppi** [comment]
The behaviour @MelanX describes is how I anticipated the mechanical daisy to work when I implemented it in the first place. So I would vote for the current behaviour being treated as a bug (that apparently existed since the very first release) and therefore just fix it up (Which should be as easy as adding a `this.workingTicks[i] >= 0` into [this condition](https://github.com/MelanX/botanical-machinery/blob/420c8b0bc8bd506ff2f6400dcce451b78c60ae91/src/main/java/de/melanx/botanicalmachinery/blocks/tiles/TileMechanicalDaisy.java#L73)).

Also, I don't see a good reason for the botanical daisy to just keep on crafting as long as possible. I would guess that in 99% of the cases this is not what you want and every other machine in the mod also stops crafting after a single iteration.
