### ISSUE TITLE
[1.20.1] Mechanical Runic Altar item duping

### ISSUE THREAD

**Issue by BOLTMAGIC** [MelanX/botanical-machinery#72]
### Minecraft version

None

### Botanical Machinery version

1.20.1 3.0.4

### LibX version

1.20.1 5.0.14

### Botania version

1.20.1 466-Forge

### Forge version

47.3.11

### The latest.log file

.

### Issue description

![1](https://github.com/user-attachments/assets/6348bfe7-62b1-4b62-8091-882e72bd43c4)
for every craft u do inside the runic altar you get the runes back.

### Steps to reproduce

download the mods and jei for easier setup
place the items inside the mechanical runic altar and insert some mana.
2x mana diamond
1x rune of winter
1x rune of earth
1x livingrock

the output is 
1x rune of winter
1x rune of earth
1x rune of wrath

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the resultItems method in BlockEntityMechanicalRunicAltar to not return runes used in crafting, fixing the issue where runes were being duplicated after each craft.

I also created pull request: https://github.com/ChaoticTrials/BotanicalMachinery/pull/73


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by MelanX** [comment]
This is intended since Botanias own altar does the same.
